### ISSUE TITLE
BUG - Wired 

### ISSUE THREAD

**Issue by Hungler** [darkinghb/OblivionIssues#38]
**WIRED** **Condição** **negativa:** **não** **têm** **usuários** **em** **cima**
 
Era para o dado apagar o número assim que não estivesse nenhum usuário em cima de nenhum dos módulos pura branco, mas o wired não está pegando.

(https://prnt.sc/jitdtg)

**Comment by darkinghb** [comment]
Resolvido (Próxima update)
