### ISSUE TITLE
New Command

### ISSUE THREAD

**Issue by Phibred** [darkinghb/OblivionIssues#42]
Olá Dark,

Precisamos de um comando tipo o :reward, só que para a rádio realizar pagamento de premiações! Nesse comando tem que executar os seguintes comandos:

Dar 5 diamantes + 1 Ponto no Hall da Rádio

Esse comando pode ser liberado par Rank: 3 / 9 / 10 / 11

Desde já agradeço!

**Comment by darkinghb** [comment]
Comando já existente, chama-se :rpoints
