### ISSUE TITLE
Wired

### ISSUE THREAD

**Issue by Robertafks** [darkinghb/OblivionIssues#53]
Efeito Wired: sair da equipe (Ao clicar no mesmo, dá dc.)
Wireds de pontuação (Não estão contando os pontos)
Ativador Wired: Habbo diz algo (Ao flodar a palavra do wired o usuário fica mutado)

obs: muitos wireds no quarto fazem com que ele fique lagado

**Comment by darkinghb** [comment]
Resolvido a questão do ativador, preciso de mais informações sobre o lag.
